---
title: "modeling"
author: "Ruoyuan Qian"
date: "4/20/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(caret)
library(Rmisc)
library(corrplot)
library(FNN)
library(pdp)
library(earth)
library(sandwich)
library(stargazer)
library(GGally)
library(patchwork)
library(MASS)
library(tidyverse)
```

```{r}
fifa_model = read_csv2("fifa_model.csv")
```

```{r }

fit.all = 
lm(log_value_eur ~ age + league_name + overall + preferred_foot + team_position + pace + shooting + passing + dribbling + dribbling, data = fifa_model)

null = lm(log_value_eur ~ 1, data = fifa_model)
full = lm(log_value_eur ~ age + league_name + overall + preferred_foot + team_position + pace + shooting + passing + dribbling + dribbling + defending + physic + BMI, data = fifa_model)

#stepAIC(object = null, scope = list(upper = full),
#        direction = "forward", k = 2)
#
#stepAIC(object = null, scope = list(upper = full),
#        direction = "forward", k = log(2756))
#
#stepAIC(object = full, scope = list(upper = full),
#        direction = "backward", k = log(2756))
#
#stepAIC(object = null, scope = list(upper = full),
#        direction = "both", k = log(2756))
```


Final model
```{r}
#FinaL MODEL FOR stepwise

#fit.AIC.fw = lm(formula = log_value_eur ~ overall + age + shooting + team_position + 
#    league_name + physic + defending + dribbling, data = fifa_model)

fit.BIC.fw = lm(formula = log_value_eur ~ overall + age + shooting + team_position, 
    data = fifa_model)

fit.BIC.bw = lm(formula = log_value_eur ~ age + overall + team_position + 
    shooting + defending + physic, data = fifa_model)

fit.BIC.sw = lm(formula = log_value_eur ~ overall + age + shooting + team_position, 
    data = fifa_model)

# Stepwise is same as forward
```


```{r}
require(broom)
Model_sum<-bind_rows(glance(null),
                     glance(full),
                     glance(fit.BIC.fw),
                     glance(fit.BIC.bw),
                     glance(fit.BIC.sw))%>%
  round(.,3)
Model_sum$names<-c("Intercept",
                   "Full",
                   "BIC Forward",
                   "BIC Backward",
                   "BIC Stepwise")
names(Model_sum)
Model_sum %>%
  dplyr::select(names, r.squared, adj.r.squared,AIC, BIC, sigma,df, df.residual)
```

# cv

```{r}
set.seed(6950)
tran.control = trainControl(method = "cv",number = 10)

fit.BIC.fw.cv = train(
  log_value_eur ~ overall + age + shooting + team_position, 
              fifa_model, method = "lm", 
              trControl = tran.control)

fit.BIC.bw.cv = train(
  log_value_eur ~ age + overall + team_position + shooting + defending + physic, 
              fifa_model, method = "lm", 
              trControl = tran.control)

resamp <- resamples(list(BIC.fw = fit.BIC.fw.cv,
                         BIC.bw = fit.BIC.bw.cv))
#summary(resamp)

bwplot(resamp, metric = "RMSE")

# select bardward : fit.BIC.bw
# param 6

n.param = dim(fifa_model)[1]- fit.BIC.bw$df.residual
```


# Model diagnosis

```{r echo = FALSE, message = F, warning = F, fig.height = 7}

model_diag =augment(fit.BIC.bw, fifa_model) %>% mutate(.ti = rstudent(fit.BIC.bw))
base = model_diag %>% 
#  rownames_to_column("case") %>% 
  ggplot(aes(x = as.numeric(X1))) +
  xlab("case id") + geom_point() + 
 geom_segment(yend = 0, aes(xend = as.numeric(X1)))


(base + aes(y = .hat) + ylab("leverage") + geom_hline(data = tibble(threshold = c("2p/n", "3p/n"), ref = c(2*3/dim(fifa_model)[1], 3*3/dim(fifa_model)[1])), aes(yintercept = ref, color = threshold))) /
 (base + aes(y = .cooksd, color = team_position) + ylab("Cook's distance")) / 
 (base + aes(y = .ti, color = team_position) + ylab("Studentized residuals") + 
    geom_hline(yintercept = 0, linetype = "dashed") +
    #geom_text(aes(label="X",x=2035,y=-6.138861))+
  geom_hline(yintercept = qt(1 - (0.05/(2*dim(fifa_model)[1])), df = dim(fifa_model)[1]-n.param  - 1), linetype = "dotted") +
  geom_hline(yintercept = qt((0.05/(2*dim(fifa_model)[1])), df = dim(fifa_model)[1]-n.param - 1), linetype = "dotted")) 
```


```{r echo = FALSE, message = F, warning = F, fig.height= 7}

res <- residuals(fit.BIC.bw)
fits <- fitted(fit.BIC.bw)

#par(mfrow=c(5,2))
par(mfrow=c(4,3), cex=0.75, mar=c(4,4,1,1), bty="L")

qqnorm(fit.BIC.bw$residuals,
       xlab="Normal quantiles", ylab="Sample quantiles", main="")
qqline(fit.BIC.bw$residuals)
#hist(fit.BIC.bw$residuals, xlab="Residuals", main="")
plot(y=model_diag %>% pull(.resid) , x=model_diag %>% pull(.fitted),xlab="Residual", ylab="Fitted")
abline(h=0,col="red")

#par(mfrow=c(3,3), cex=0.75, mar=c(4,4,1,1), bty="L")

#plot(fits, res)
#abline(h=0, col="gray")

boxplot(res ~ fifa_model$age)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$league_name)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$overall)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$team_position)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$shooting)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$dribbling)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$defending)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$physic)
abline(h=0, col="gray")

#qqnorm(res, xlim=c(-5,5))
#qqline(res)
```

All age >30, and majority of them are defender. Therefore, we want to investigate whether there are interaction effects between team postion and age. 

```{r}
fit.BIC.quart<-lm(formula = log_value_eur ~ poly(age,2) + league_name +  poly(overall,2) + team_position + 
    shooting + dribbling + defending + physic, data = fifa_model)

summary(fit.BIC.quart)
```


```{r}
#fit.BIC.interact<- lm(formula = log_value_eur ~ poly(age,2) + league_name + overall * team_position + 
#    shooting + dribbling + defending + physic, data = fifa_model)
#summary(fit.BIC.interact)
#
#summary(lm(data=fifa_mode))
```

```{r, fig.height= 9, fig.width=8}
res <- residuals(fit.BIC.quart)
fits <- fitted(fit.BIC.quart)

#par(mfrow=c(5,2))
par(mfrow=c(4,3), cex=0.75, mar=c(4,4,1,1), bty="L")

qqnorm(fit.BIC.quart$residuals,
       xlab="Normal quantiles", ylab="Sample quantiles", main="")
qqline(fit.BIC.quart$residuals)
#hist(fit.BIC.bw$residuals, xlab="Residuals", main="")
plot(y=model_diag %>% pull(.resid) , x=model_diag %>% pull(.fitted),xlab="Residual", ylab="Fitted")
abline(h=0,col="red")

#par(mfrow=c(3,3), cex=0.75, mar=c(4,4,1,1), bty="L")

#plot(fits, res)
#abline(h=0, col="gray")

boxplot(res ~ fifa_model$age)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$league_name)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$overall)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$team_position)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$shooting)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$dribbling)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$defending)
abline(h=0, col="gray")

boxplot(res ~ fifa_model$physic)
abline(h=0, col="gray")

```

# Partial F test

Compare Backward model and Ploy model

```{r}
anova(fit.BIC.bw,fit.BIC.quart)
```


```{r Appendix XX}
# Appendix XX
model_diag %>%
  dplyr::select(short_name,log_value_eur, age, league_name, overall,team_position,shooting,
         dribbling,defending,physic,.ti) %>%
  filter(abs(.ti) > abs(qt((0.05/(2*dim(fifa_model)[1])), df = dim(fifa_model)[1]-9 - 1))) %>% 
  knitr::kable()
```